### ISSUE TITLE
Checkpoint for Training

### ISSUE THREAD

**Issue by wusize** [cientgu/InstructDiffusion#12]
Hi!

Thanks for your impressive work! I am trying to run the task-specific training and need to load the checkpoint generated in the [adaptation phase](https://github.com/cientgu/InstructDiffusion/blob/main/configs/instruct_diffusion.yaml#L11). Could you please provide this checkpoint?

**Comment by wusize** [comment]
By the way, the [`data.base.Txt2ImgIterableBaseDataset`](https://github.com/cientgu/InstructDiffusion/blob/main/main.py#L30) doesn't seem to be defined under `stable_diffusion/ldm`. I meet the following error message when running the training code.
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ModuleNotFoundError: No module named 'ldm.data'
```

**Comment by wusize** [comment]
> By the way, the [`data.base.Txt2ImgIterableBaseDataset`](https://github.com/cientgu/InstructDiffusion/blob/main/main.py#L30) doesn't seem to be defined under `stable_diffusion/ldm`. I meet the following error message when running the training code.
> 
> ```
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ModuleNotFoundError: No module named 'ldm.data'
> ```

It might because you add `data/` in  `.gitignore`.

**Comment by YerongLi** [comment]
Same error running the training workflow, how did you resolve this?

```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    from ldm.data.base import Txt2ImgIterableBaseDataset
ModuleNotFoundError: No module named 'ldm.data'
```

**Comment by YerongLi** [comment]
These files are from latent diffusion.
