### ISSUE TITLE
What is meta_info.json for GPA gqa-inplant dataset not found

### ISSUE THREAD

**Issue by YerongLi** [cientgu/InstructDiffusion#21]
```
    |-- gqa-inpaint
    |   |-- images
    |   |-- images_inpainted
    |   |-- masks
    |   |-- train_scenes.json
    |   `-- meta_info.json
    `-- MagicBrush
        |-- data
        |-- processed-train
        `-- magic_train.json
```

- How to obtain meta_info.json file fromt the gqa-inplant dataset
- Also how to obtain the prepocessed-train for magicBrush?

**Comment by YerongLi** [comment]
```
(instructdiff) yerong2@ InstructDiffusion$ ls data/GIER_editing_data/
filtered_meta_new.pt  GIER.json  GIER_new.json  images  input_does_not_exist.txt  output_does_not_exist.txt  preprocess.py
```

Also I am not sure how the GIER_new.json is constructed?

I am meeting error when trying to map the "request" to "prompt"

```
Traceback (most recent call last):
  File "main.py", line 561, in <module>
    data_loader_train.sampler.set_epoch(epoch)
  File "main.py", line 291, in train_one_epoch
    for idx, batch in enumerate(data_loader):
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 350, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/yerong2/InstructDiffusion/dataset/pose/pose.py", line 162, in __getitem__
    data_numpy = cv2.cvtColor(data_numpy, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by TiankaiHang** [comment]
Hi,

I found one version of the meta_info.json and uploaded it here.

https://github.com/TiankaiHang/storage-2023/releases/download/0924/meta_info.json

Hope this could help you.

Best.

**Comment by YerongLi** [comment]
Thanks let me have a try!

**Comment by xushilin1** [comment]
> ```
> (instructdiff) yerong2@ InstructDiffusion$ ls data/GIER_editing_data/
> filtered_meta_new.pt  GIER.json  GIER_new.json  images  input_does_not_exist.txt  output_does_not_exist.txt  preprocess.py
> ```

Hello, where can I find these files?
